[tool.poetry]
name = "aconai"
version = "0.1.0"
description = ""
authors = ["Adam Cataldo"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
